services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gridpulse
      POSTGRES_USER: gridpulse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase
    ports:
      - "3002:3000"
    volumes:
      - metabase-data:/metabase.db
    depends_on:
      - postgres

volumes:
  pgdata:
  metabase-data:


