[project]
name = "gridpulse"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "psycopg[binary]",
    "python-dotenv",
    "dagster",
    "tzdata",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]